components:
  schemas:
    cart:
      type: object
      properties:
        products:
          type: array
          description: Array con productos y su cantidades.

  responses:
    registerCart:
      description: Respuesta al crear un carrito
      type: object
      properties:
        code:
          type: number
          description: Código de estado de la solicitud
        error:
          type: boolean
          description: Estado de la solicitud
        msg:
          type: string
          description: Mensaje de respuesta
        cart:
          $ref: "#/components/schemas/cart"
      example:
        code: 200,
        error: false
        msg: "Carritos encontrados"
        cart:
          products:
            _id: "64dbd0afa30dd5cce4dec12a"
            quantity: 1
    cartList:
      description: Respuesta al solicitar una lista de carritos
      type: object
      properties:
        code:
          type: number
          description: Código de estado de la solicitud
        error:
          type: boolean
          description: Estado de la solicitud
        msg:
          type: string
          description: Mensaje de respuesta
        cart:
          type: object
          description: Objeto con la data de los carritos
      example:
        code: 200
        error: false
        msg: "carritos encontrados"
        cart:
          _id: "64dbd0afa30dd5cce4dec12a"
          quantity: 1
          __v: 0
    errorResponses:
      notFound:
        description: Respuesta cuando no se encuentra el carrito
        content:
          application/json:
            schema:
              type: object
              properties:
                code: 404
                error:
                  type: boolean
                  description: Estado de la solicitud
                msg:
                  type: string
                  description: Descripción del error
              example:
                code: 404
                error: true
                msg: "carrito no encontrado"
    handler:
      description: Respuesta de error interno del servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: boolean
                description: Estado de la solicitud
              message:
                type: string
                description: Descripción del error
            example:
              error: true
              message: "Error interno del servidor"

paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carts
      requestBody:
        required: true
        description: Objeto con las propiedades del carrito
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cart"
      responses:
        "201":
          description: Carrito creado satisfactoriamente
          content:
            application/json:
              schema:
                $ref: "#/components/responses/registerCart"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"

    get:
      summary: Obtener una lista de todos los carritos
      tags:
        - Carts
      responses:
        "200":
          description: Lista de carritos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cartList"
              example:
                code: 200
                error: false
                msg: "Carritos encontrados"
                cart:
                  _id: "64dbd0afa30dd5cce4dec12a"
                  quantity: 1
                  __v: 0
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"

  /api/carts/{id}:
    get:
      summary: Obtener un carrito por ID
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          description: ID del carrito a buscar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Carrito encontrado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cart"
              example:
                code: 200
                error: false
                msg: "Carrito encontrado"
                cart:
                  _id: "64dbd0afa30dd5cce4dec12a"
                  quantity: 1
                  __v: 0
        "404":
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/notFound"
              example:
                code: 404,
                error: true
                msg: "Carrito no encontrado"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"

    put:
      summary: Actualizar un carrito por ID
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          description: ID del carrito a actualizar
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Objeto con las propiedades actualizadas del carrito
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/cart"
      responses:
        "200":
          description: Carrito actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/responses/cart"
              example:
                code: 200
                error: false
                msg: "Carrito actualizado"
                cart:
                  _id: "64dbd0afa30dd5cce4dec12a"
                  quantity: 1
                  __v: 0
        "404":
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/notFound"
              example:
                code: 404,
                error: true
                msg: "Carrito no encontrado"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"

    delete:
      summary: Eliminar un carrito por ID
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          description: ID del carrito a eliminar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Carrito eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/responses/registerCart"
              example:
                code: 200
                error: false
                msg: "Carrito eliminado con éxito"
                cart:
                  _id: "64dbd0afa30dd5cce4dec12a"
                  quantity: 1
                  __v: 0
        "404":
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/notFound"
              example:
                code: 404,
                error: true
                msg: "Carrito no encontrado"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"
