components:
  schemas:
    ticket:
      type: object
      properties:
        code:
          type: string
          description: codigo del ticket
        purchase_datetime:
          type: string
          description: Fecha y hora de compra
        amount:
          type: number
          description: Total de la compra
        purchaser:
          type: string
          description: Correo del comprador
      required:
        - code
        - purchase_datetime
        - amount
        - purchaser

  errorResponses:
    handler:
      description: Respuesta de error interno del servidor
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: boolean
                description: Estado de la solicitud
              message:
                type: string
                description: Descripción del error
            example:
              error: true
              message: "Error interno del servidor"

paths:
  /api/auth/ticket:
    post:
      summary: Crear un nuevo ticket
      tags:
        - Ticket
      requestBody:
        required: true
        description: Objeto con las propiedades de la compra
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ticket"
      responses:
        "201":
          description: El ticket se ha creado exitosamente
          content:
            application/json:
              example:
                code: 201,
                msg: "Ticket creado"
                ticket:
                  code: "xxxxxxx"
                  purchase_datetime: "00:00:00 00/00/00"
                noStock:
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/handler"